name: notify.events message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message
        uses: notify-events/github-action@main
        with:
          token: ${{secrets.TELEGRAM_TOKEN }}
          text:  This is message
