name: Telegram
on: [ push ]
jobs:
  test:
    name: pytest
    runs-on: ubintu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt pytest
      - run: pytest
      - name: 'telegram notification'
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_CHAT_ID }}
          token: ${{secrets.TELEGRAM_TOKEN }}
          message:|
          all is ok
